In [39]:
import numpy as np

# The basic


In [3]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
b=np.array([[1,2,4],[4,5,8],[10,11,12]])
print(b)

[[ 1  2  4]
 [ 4  5  8]
 [10 11 12]]


In [5]:
#get dimension of an array/matrix
a.ndim, b.ndim

(1, 2)

In [6]:
b.ndim

2

In [7]:
#get shape
b.shape

(3, 3)

In [12]:
#get size
a.dtype # it can also be changed while defining array like a=np.array([1,2,3],dtype='int16')

dtype('int32')

In [15]:
a.dtype

dtype('int16')

In [18]:
#to get the item size
a.itemsize

4

In [19]:
#number of bytes in
a.nbytes

12

# accessing, changing and manipulating the rows and columns datas


In [6]:
b=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])# this is accesssing through numpy array
print(b)                     

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [34]:
#get items of array
print(b[0,4])
print(b[1,4])

5
12


In [37]:
#get specific row or column
print(b[0,:]) # this syntax is same as MATLab

[1 2 3 4 5 6 7]


In [10]:
print(b[:,:])

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [16]:
print(b)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [17]:
print(b[:,1])

[2 9]


In [20]:
# little bit of complex
# in list this is simple like
mylist=[1,2,3,4,5,6] # if we want to print 2,4,6 then we do like this
print(mylist[1:6:2])

[2, 4, 6]


In [22]:
#but in numpy syantax is bit different
print(b)
print(b[0, 1:6:2])

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
[2 4 6]


In [23]:
# chaning the value of matrxi
b[:,5]=5
print(b)

[[ 1  2  3  4  5  5  7]
 [ 8  9 10 11 12  5 14]]


# 3D-array


In [4]:
import numpy as np
arr=np.array([1,2,3])
print(arr)
var=np.array([[1,2,3,4],[4,5,6,7]])
print(var)
car=np.array([[[1,2,3,4],[4,5,6,8]],[[9,10,11,12],[13,14,15,16]]])
print(car)

[1 2 3]
[[1 2 3 4]
 [4 5 6 7]]
[[[ 1  2  3  4]
  [ 4  5  6  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


In [5]:
print(car[1,:,2]) # firts of all i will see second matrix ,and then i will see all of its row and then see 3rd(2) column element

[11 15]


# introduction to different types of matrices


In [8]:
np.zeros((2,3))  # zero matrix

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.ones((2,2,2))  # ones matrix

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [10]:
#any other numbered matrix
np.full((2,3),14)

array([[14, 14, 14],
       [14, 14, 14]])

In [11]:
# to generate random interger matrix
np.random.rand(4,3)

array([[0.2300049 , 0.82263926, 0.77424961],
       [0.70779185, 0.37886506, 0.6000882 ],
       [0.47730827, 0.46220486, 0.36948369],
       [0.92403083, 0.84420818, 0.84614856]])

In [13]:
# random value with integer
np.random.randint(6,size=(3,3)) # generates the random values below 5 with size 3x3

array([[2, 3, 1],
       [3, 5, 5],
       [0, 0, 3]])

In [15]:
# identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
# repeat an array
tor=np.array([[1,2,3]])
tor.ndim
tor.shape
new=np.repeat(tor,3,axis=0)
print(new)
new.shape

[[1 2 3]
 [1 2 3]
 [1 2 3]]


(3, 3)