In [1]:
import numpy as np


In [2]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [3]:
np.arange(4,10)

array([4, 5, 6, 7, 8, 9])

In [4]:
np.arange(4,10).max()

9

In [5]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
b=np.array([[1,2,3,4],[5,6,7,8]])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [11]:
b[:,3]
b.size
b.shape
b.ndim

2

In [21]:
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [22]:
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
for i in range(3):
    for k in range(3):
        if a[i,k]==1:
            k+=1
        else:
            a[i,k]=1
    
print(a)
            

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [30]:
mylist=[[1,2,3,4,5],[6,7,8,9]]
print(mylist[0][0])


1


In [32]:
c=np.arange(1,10)
print(c)

[1 2 3 4 5 6 7 8 9]


In [40]:
print(c[1:10:2])

[2 4 6 8]


In [43]:
#one-D
np.zeros(3)

array([0., 0., 0.])

In [44]:
#2D array
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [45]:
np.full((3,4),5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

   # PANDAS REVISION
   

In [46]:
import pandas as pd

In [47]:
data_frame=pd.read_excel('H:\\python documentation\\cars.xlsx')
data_frame.head(10)

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0         130    3504          12.0   
1  15.0          8         350.0         165    3693          11.5   
2  18.0          8         318.0         150    3436          11.0   
3  16.0          8         304.0         150    3433          12.0   
4  17.0          8         302.0         140    3449          10.5   
5  15.0          8         429.0         198    4341          10.0   
6  14.0          8         454.0         220    4354           9.0   
7  14.0          8         440.0         215    4312           8.5   
8  14.0          8         455.0         225    4425          10.0   
9  15.0          8         390.0         190    3850           8.5   

   model_year  origin                   car_name  
0          70       1  chevrolet,chevelle,malibu  
1          70       1          buick,skylark,320  
2          70       1         plymouth,satellite  
3          70       1              amc,rebel,sst  
4          70       1                ford,torino  
5          70       1           ford,galaxie,500  
6          70       1           chevrolet,impala  
7          70       1          plymouth,fury,iii  
8          70       1           pontiac,catalina  
9          70       1         amc,ambassador,dpl

In [53]:
# grouping the data to see more clearly
data_frame['car_name']

0      chevrolet,chevelle,malibu
1              buick,skylark,320
2             plymouth,satellite
3                  amc,rebel,sst
4                    ford,torino
                 ...            
387              ford,mustang,gl
388                    vw,pickup
389                dodge,rampage
390                  ford,ranger
391                   chevy,s-10
Name: car_name, Length: 392, dtype: object

In [64]:
data_frame.groupby(['car_name']).max().sort_values('cylinders',ascending=False)


mpg  cylinders  displacement  horsepower  weight  \
car_name                                                                     
amc,ambassador,brougham  13.0          8         360.0         175    3821   
ford,torino              17.0          8         302.0         140    3449   
mercury,cougar,brougham  15.0          8         302.0         130    4295   
mercury,grand,marquis    16.5          8         351.0         138    3955   
mercury,marquis          11.0          8         429.0         208    4633   
...                       ...        ...           ...         ...     ...   
vw,rabbit,custom         31.9          4          89.0          71    1925   
maxda,rx3                18.0          3          70.0          90    2124   
mazda,rx-4               21.5          3          80.0         110    2720   
mazda,rx-7,gs            23.7          3          70.0         100    2420   
mazda,rx2,coupe          19.0          3          70.0          97    2330   

                         acceleration  model_year  origin  
car_name                                                   
amc,ambassador,brougham          11.0          73       1  
ford,torino                      10.5          70       1  
mercury,cougar,brougham          14.9          77       1  
mercury,grand,marquis            13.2          79       1  
mercury,marquis                  11.0          72       1  
...                               ...         ...     ...  
vw,rabbit,custom                 14.0          79       2  
maxda,rx3                        13.5          73       3  
mazda,rx-4                       13.5          77       3  
mazda,rx-7,gs                    12.5          80       3  
mazda,rx2,coupe                  13.5          72       3  

[301 rows x 8 columns]

In [69]:
data_frame.groupby(['car_name']).max().sort_values(['cylinders','horsepower','model_year'],ascending=[False,False,False])

mpg  cylinders  displacement  horsepower  \
car_name                                                                  
pontiac,grand,prix            16.0          8         400.0         230   
buick,estate,wagon,(sw)       16.9          8         455.0         225   
pontiac,catalina              16.0          8         455.0         225   
buick,electra,225,custom      12.0          8         455.0         225   
chevrolet,impala              14.0          8         454.0         220   
...                            ...        ...           ...         ...   
volkswagen,1131,deluxe,sedan  26.0          4          97.0          46   
mazda,rx-4                    21.5          3          80.0         110   
mazda,rx-7,gs                 23.7          3          70.0         100   
mazda,rx2,coupe               19.0          3          70.0          97   
maxda,rx3                     18.0          3          70.0          90   

                              weight  acceleration  model_year  origin  
car_name                                                                
pontiac,grand,prix              4278           9.5          73       1  
buick,estate,wagon,(sw)         4360          14.9          79       1  
pontiac,catalina                4668          12.0          75       1  
buick,electra,225,custom        4951          11.0          73       1  
chevrolet,impala                4997          14.0          73       1  
...                              ...           ...         ...     ...  
volkswagen,1131,deluxe,sedan    1835          20.5          70       2  
mazda,rx-4                      2720          13.5          77       3  
mazda,rx-7,gs                   2420          12.5          80       3  
mazda,rx2,coupe                 2330          13.5          72       3  
maxda,rx3                       2124          13.5          73       3  

[301 rows x 8 columns]

In [71]:
data_frame.groupby(['car_name']).max().sort_values('model_year', ascending=False)

mpg  cylinders  displacement  horsepower  weight  \
car_name                                                                   
pontiac,phoenix        33.5          4         151.0          90    2735   
buick,century,limited  25.0          6         181.0         110    2945   
mazda,glc,custom,l     37.0          4          91.0          68    2025   
mazda,glc,custom       31.0          4          91.0          68    1970   
honda,civic,(auto)     32.0          4          91.0          67    1965   
...                     ...        ...           ...         ...     ...   
ford,torino            17.0          8         302.0         140    3449   
toyota,corona,mark,ii  24.0          4         113.0          95    2372   
chevrolet,monte,carlo  15.0          8         400.0         150    3761   
hi,1200d                9.0          8         304.0         193    4732   
ford,f250              10.0          8         360.0         215    4615   

                       acceleration  model_year  origin  
car_name                                                 
pontiac,phoenix                18.0          82       1  
buick,century,limited          16.4          82       1  
mazda,glc,custom,l             18.2          82       3  
mazda,glc,custom               17.6          82       3  
honda,civic,(auto)             15.7          82       3  
...                             ...         ...     ...  
ford,torino                    10.5          70       1  
toyota,corona,mark,ii          15.0          70       3  
chevrolet,monte,carlo           9.5          70       1  
hi,1200d                       18.5          70       1  
ford,f250                      14.0          70       1  

[301 rows x 8 columns]

In [75]:
data_frame.loc[data_frame['origin']].count()

mpg             392
cylinders       392
displacement    392
horsepower      392
weight          392
acceleration    392
model_year      392
origin          392
car_name        392
dtype: int64

In [76]:
data_frame.head(5)

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0         130    3504          12.0   
1  15.0          8         350.0         165    3693          11.5   
2  18.0          8         318.0         150    3436          11.0   
3  16.0          8         304.0         150    3433          12.0   
4  17.0          8         302.0         140    3449          10.5   

   model_year  origin                   car_name  
0          70       1  chevrolet,chevelle,malibu  
1          70       1          buick,skylark,320  
2          70       1         plymouth,satellite  
3          70       1              amc,rebel,sst  
4          70       1                ford,torino

In [78]:
data_frame.iloc[0:5,0:3]

mpg  cylinders  displacement
0  18.0          8         307.0
1  15.0          8         350.0
2  18.0          8         318.0
3  16.0          8         304.0
4  17.0          8         302.0